[package]
name = "goto"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "gotoctl"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
clap = { version = "4.0", features = ["derive"] }
dirs = "4.0"
