[package]
name = "goto"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "goto_rs"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.75"
dirs = "5.0.1"
serde = { version = "1.0.188", features = ["derive"] }
serde_yaml = "0.9.25"
skim = "0.10.4"
